apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-api
  template:
    metadata:
      labels:
        app: fraud-api
    spec:
      containers:
      - name: fraud-api
        image: fraud-serve:0.1
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      volumes:
      - name: model-volume
        hostPath:
          path: /models  # will mount model file later
