FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src ./src
# model will be mounted at /app/models
ENV MODEL_PATH=/app/models/xgb_fraud.joblib
EXPOSE 8000
CMD ["python","-m","uvicorn","src.serve.app:app","--host","0.0.0.0","--port","8000"]
